### ISSUE TITLE
Why use loadJSDeferred

### ISSUE THREAD

**Issue by botev** [qwtel/hydejack#14]
So, I've noticed that whenever in the config we have `load_google_fonts` when each page loads the following happens:

1. Page loads (some ms)
2. All fonts change from default one to the google font, which could include a small rescaling (some ms)
3. The social network icons get drawn, which could slightly push the other text in the nav bar up.

So this basically leads to the `loadJSDeferred`. I was just wondering why is it the case, specially for a very fast static page, that you want to deffered it?

PS: Just to explain how I fixed it: I've removed the deferred load from site js and google fonts, made the body hidden, and on window.load made the body visible. Even with slow internet this loads extremely fast, but there are no visible glitches happening.

**Comment by qwtel** [comment]
hi. it's funny, this is one of these cases were I think of something as a feature while others see it as a bug :) deferring the javascript is done because I didn't want any requests to prevent the page from rendering, so that the content is visible immediately. More about it [here](https://varvy.com/pagespeed/defer-loading-javascript.html). As a side effect, the layout shifts a couple of times, as you've described (also known as Flash Of Unstyled Text FOUT, or Flash Of Unstyled Content FOUC. More [here](https://css-tricks.com/fout-foit-foft/)).

It's a debated question and there is no obvious correct solution. I've decided to go with the one that is the least punishing for visitors with slow connections. However, I was annoyed by the flashing as well, which is why the next version will reload pages via JS and HTML5 push state. It also has some nice page transitions. You can [see it live here](https://qwtel.com/hydejack/) and get the code from the [v6 branch](https://github.com/qwtel/hydejack/tree/v6). However, the layout will still shift on the first request though.

A couple of tips regarding your solution:

Write the onload callback as "defensive" as possible. Different browsers support different ways of adding callbacks. Also, hide the body via JS, so that people who have JS disabled don't see an empty page. Something like (not tested):

```html
<script>
document.body.style.display = 'none';
function makeBodyVisible() { document.body.style.display = 'block'; }
if (window.addEventListener) window.addEventListener("load", makeBodyVisible, false);
else if (window.attachEvent) window.attachEvent("onload", makeBodyVisible);
else window.onload = makeBodyVisible;
</script>
```

hope this helps.

**Comment by botev** [comment]
Ah thanks a lot!. I think I will directly form the v6 as it seems really better:+1:. I still might add your suggestion such that even the first page does not glitch, however, I add it as an option to specify in the config. I also used "visibility" rather than "display" as somehow it works better (I think because the display does not even create the element and things get redrawn later, but probably I'm wrong). 

You are right that I should have probably call not the deferred load the problem, but the actual visual glitching. 

On a totally different note, it would be good in the config to have an option for adding an `Archive` link in the navigation bar.

**Comment by qwtel** [comment]
Glad you like it 😄 . 

So far, I'm not sure about making this approach part of the repo. Also, I've heard the AMP project has a better approach to loading webfonts, but I so far I haven't looked into it.

> I think because the display does not even create the element and things get redrawn later

Yes, that's almost what's happening. `display: none` creates the elements in memory, but the elements are not part of the layout process. `visibility` will include the elements in the layout, but will not paint them. 

> On a totally different note, it would be good in the config to have an option for adding an Archive link in the navigation bar.

In v6 that's possible by creating an `archive.md` file and adding 

```yml
---
layout: list
title: Archive
menu: true
# order: x 
---
```

The `order` key is optional. `x` is the number where you'd like the link to appear, but this depends on the `order` of all other links in the sidebar. For more, see [the documentation](https://qwtel.com/hydejack/docs/6.0.0-beta3/basics/#adding-an-entry-to-the-sidebar).

This will render a list of all posts (but not pages).

**Comment by botev** [comment]
Thanks a lot. I will close the issue and let's hope the `v6` will soon be officially released so everyone can get this nice updates!
