### ISSUE TITLE
8.2.0 released?

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#142]
I see it referenced in the change log on hydejack.com, but see no branch here, and didn’t receive a PRO release email.

**Comment by MilovanTomasevic** [comment]
I also saw it. And another question is that I do not open a new topic, whether it is possible to get **`index.md`** file from [hydejack.com](https://hydejack.com) I tried to put everything on one page, but I did not succeed. so if I can get it on mail [tomas.ftn.e2@gmail.com](mailto: tomas.ftn.e2@gmail.com). Otherwise I use pro version and it's great :)

**Comment by qwtel** [comment]
accidently published this. 8.2.0 finally release now.
