### ISSUE TITLE
use script defer?

### ISSUE THREAD

**Issue by Trass3r** [qwtel/hydejack#145]
Brings guaranteed execution order and seems to be widely supported: https://caniuse.com/#feat=script-defer

My use-case is adding https://katex.org/docs/autorender.html (edit: or other katex extensions) for single dollar sign inline math via my-head.html which does not work currently because it seems to be run before the main katex script has.

**Comment by qwtel** [comment]
The autorender extension looks interesting. Hydejack basically implements the same thing (the extension didn't exist when I built it). 

What are you trying to achieve here? Getting this to work with Hydejack's dynamic page loading will be more difficult than just adding the script.

**Comment by qwtel** [comment]
Okay, KaTeX certainly changed since I last looked at it. I think it would make sense to include these extensions in Hydejack by default.

**Comment by rriemann** [comment]
At the moment, I try to add to my page https://blog.riemann.cc the header `Content-Security-Policy` to get good points at <https://observatory.mozilla.org/>.

Test here: <https://observatory.mozilla.org/analyze/hydejack.com>

One gets many minus points when adding `'unsafe-inline'` in `style-src` and `script-src`.

I think when using the browser inbuilt `defer` function, this can be one step towards avoiding unsafe inline script code for this template.

More info on this header: <https://content-security-policy.com/>

**Comment by Trass3r** [comment]
> Okay, I looked at it some more, and KaTeX certainly changed since the last time I checked. I think it would make sense to include these extensions in Hydejack by default.

Any news on that?

**Comment by qwtel** [comment]
I took a look at this and concluded that it's not a fit. The autorender plugin would not detect Hydejack's dynamic content replacement, and hydejack already does pretty much the same as autorender.

Also, I re-read your question and I think there shouldn't be any math in `my-head.html`. This section goes into the `<head>` of the document, which isn't for rendered content. But the same might happen if you put it into `my-body.html` since Hydejack's version of autorender only looks inside articles I think. 

Keeping this open for now

**Comment by qwtel** [comment]
> Probably should look for math on the entire document once after the document loads. Keeping this open for now

Checked the code and it already does this. Closing
