### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by benetherington** [qwtel/hydejack#18]
Hey, Florian. I pinged you on Twitter, but it looks like you're not super active over there. The Hydejack documentation linked below is incomplete. I really like the look of your theme, and I'd like to push it to its limits!

https://qwtel.com/hydejack/docs/6.0.0/configuration/

**Comment by qwtel** [comment]
Hi, thanks for reaching out and glad you like the theme 😃 

You're absolutely right. Gladly, this bug has already been fixed in the [current version 6.1.0](https://qwtel.com/hydejack/docs/6.1.0/) (you can also find the latest documentation via [/docs/latest/](https://qwtel.com/hydejack/docs/latest/)). It should be fixed in 6.0.0 as well now.

Generally I keep the old docs around so links don't break, but I don't update them since that could be confusing. Fixing the bug you've found is a different matter though.

Feel free to open issues (or send tweets; I'll read them eventually) when you reach other limits 😉

**Comment by benetherington** [comment]
Brilliant. IDK how I got into an older version's documentation.

**Comment by qwtel** [comment]
I should probably include a warning when docs are outdated.
