### ISSUE TITLE
Blog layout broken?

### ISSUE THREAD

**Issue by benetherington** [qwtel/hydejack#19]
See branch below. I started implementing hydejack 6.1.0, but when I use the blog layout, no posts are listed. If I switch to list layout, my posts are included.

https://github.com/NotionPod/NotionPod.github.io/tree/theme-hydejack

**Comment by qwtel** [comment]
The problem is that you also kept the old `index.md` file around (in addition to `index.html`). It works when you delete it.

However, there's another problem you will run into: Including `<script>` tags in posts is not supported. It's a anti-pattern in general, as it will block the rendering of the page until the script is loaded. Additionally, since pages are loaded dynamically in Hydejack, it will not respect the order and lead to an error.

As a workaround you can use this:

```html
<script>
  loadJSDeferred('/audiojs/audio.min.js', function() {
    audiojs.events.ready(function() {
      var as = audiojs.createAll();
    });
  });
</script>

```

**Comment by benetherington** [comment]
What a champ. Thank you very much!
