### ISSUE TITLE
Markdown parsing is failing.

### ISSUE THREAD

**Issue by ManvendraSK** [qwtel/hydejack#20]
Hello, Florian. I'm using your repo hydejack as my blog theme. Could you please let me know why this is not working correctly after the merge to v6.0. Please see at https://www.manvendrask.com/2017/05/30/advanced-npm-tricks-and-fun/. The markdown has torn down the page. It's working on my local machine absolutely fine. 

I couldn't find out the reason after many attempts. 

Your help is appreciated. Thanks.

**Comment by qwtel** [comment]
Hi Manvendra,

the problem occurs somewhere during minification. You can reproduce it locally by setting `JEKYLL_ENV` to `production`, ie running

    JEKYLL_ENV=production bundle exec jekyll serve

That will come in handy when making the following changes:
Replace every occurrence of `{% highlight <lang> linenos %}` with `~~~<lang>` and every `{% endhighlight %}` with `~~~`.

For example
```
{% highlight json linenos %}
{
   "name": "npmify",
   "version": "1.0.0"
}
{% endhighlight %}
```
becomes
```
~~~json
{
   "name": "npmify",
   "version": "1.0.0"
}
~~~
```
and so on.

It's strange that `{% highlight %}` is causing this. I'll take a closer look later, but this should fix it in the meantime.

**Comment by ManvendraSK** [comment]
Thanks, @qwtel. It's working now. But I'm missing the line numbers now. :-(. This is breaking in the production build. 

One more issue is, I'm not able to see the arrow beside the continue reading link but some junk. It's same with the little squares that used to show below the post ending. 

Thaks for the help buddy.

**Comment by qwtel** [comment]
Hi,

after doing some more research I've concluded that this is pretty much unfixable. The problem is in the interaction between `jekyll-compress-html` and the output generated by Jekyll / Rouge. Nothing that theme can do about it.

Specifically, the output will contain nested `<pre>` tags which `jekyll-compress-html` can't deal with and shouldn't: Nesting `pre` is unusual, but not invalid per-se. However, putting a `table` as child of `code` is, leading me to believe that the output of `highlight` + `linenos` is simply bad (maybe it's like that for legacy reasons), but changing it would break every Jekyll theme that relies on this particular structure, so it is unlikely that any changes can be made.

Example output of `highlight` + `linenos`:

```html
<figure class="highlight"><pre><code class="language-js" data-lang="js"><table style="border-spacing: 0"><tbody><tr><td class="gutter gl" style="text-align: right"><pre class="lineno">1
2
3
4
5
6
7
8
9</pre></td><td class="code"><pre><span class="c1">// Example can be run directly in your JavaScript console</span>

<span class="c1">// Create a function that takes two arguments and returns the sum of those</span>
<span class="c1">// arguments</span>
<span class="kd">var</span> <span class="nx">adder</span> <span class="o">=</span> <span class="k">new</span> <span class="nb">Function</span><span class="p">(</span><span class="s2">"a"</span><span class="p">,</span> <span class="s2">"b"</span><span class="p">,</span> <span class="s2">"return a + b"</span><span class="p">);</span>

<span class="c1">// Call the function</span>
<span class="nx">adder</span><span class="p">(</span><span class="mi">2</span><span class="p">,</span> <span class="mi">6</span><span class="p">);</span>
<span class="c1">// &gt; 8</span><span class="w">
</span></pre></td></tr></tbody></table></code></pre></figure>
```

Related issues:
* penibelst/jekyll-compress-html#71
* jekyll/jekyll#4432

I'm afraid you'll have to live without line numbers, unless you are willing to give up HTML minification. Also, since I haven't written any CSS for line numbers, it looks broken even in the non-minified version (normal table styles apply, but they don't play well with being nested inside a `code` element...)

**Comment by qwtel** [comment]
Regarding your other issue. It seem that you don't have a font installed that includes the ['BLACK DIAMOND MINUS WHITE X' (U+2756)](http://www.fileformat.info/info/unicode/char/2756/index.htm) and ['RIGHTWARDS ARROW' (U+2192)](http://www.fileformat.info/info/unicode/char/2192/index.htm) characters. I wasn't aware that this was a possiblity. I think about including them in the icon font in a future release.

**Comment by ManvendraSK** [comment]
Thanks. So, maybe meanwhile I would have to live without line numbers. Can I download these fonts from the site you mentioned?

**Comment by qwtel** [comment]
You could download Google's [Noto font](https://www.google.com/get/noto/), which was specifically designed to solve the little boxes problem (dubbed "tofu"; noto = no tofu) but it is huge and the problem is that your readers also need the font to see the page correctly, which is unlikely. 

Now that I'm aware that this is a problem, I'll probably switch to including all icons in the icon font and not relying on unicode chars.

**Comment by ManvendraSK** [comment]
Great. For the time being, I'm using following solutions: 

1.  For right arrow: `content: " \2192";`
2.  For square box: `content: "\2756";`

And It's working fine. You might want to look at how these are looking at http://www.manvendrask.com/. 

Thanks for your support.  You are really a genius. 👍

**Comment by qwtel** [comment]
wait, do the display correctly when you use `content: " \2192";`/`content: "\2756";`?

**Comment by ManvendraSK** [comment]
Yes. Please have a look at the specified URL.

**Comment by qwtel** [comment]
I did, but for me it worked even before you made any changes ;) 

Okay, so it seems the fix is to use a different representation. 
May I ask what browser you are using?

**Comment by ManvendraSK** [comment]
:-)

Chrome 58. And some Android mobile browsers. It's working in Edge browser.
