### ISSUE TITLE
Lots of white space before content in Hydejack 6.3 with Internet Explorer 11

### ISSUE THREAD

**Issue by mfweber** [qwtel/hydejack#21]
When opening a Hydejack 6.3 page in Internet Explorer 11 (Windows 10), I am shown a blank page on the right hand side. To see any content, I have to scroll down first. The menu also flickers heavily while scrolling. Strangely, when clicking on a project-card, the whitespace error goes away (until reloading the page). A colleague experienced the same problem in IE. I have not experienced the problem in any other browser (including Edge).

I have uploaded a video of the behavior [on github](https://github.com/mfweber/mfweber.github.io/blob/master/temp/hydejack6.3_IE11_bug.mov). 

Thanks a lot for the great template!

**Comment by qwtel** [comment]
Hi. I like what you did with the fonts, very good choice :)

The problem has been fixed and will be included in the next version. You'll be notified when it is ready, maybe even later day.

In case you're interested, the problem was that I was adding CSS classes like this

```js
animationMain.classList.add('animation-main', 'fixed-top');
```

but turns out IE11 only supports adding them one-at-a-time like this

```js
animationMain.classList.add('animation-main');
animationMain.classList.add('fixed-top');
```

Regarding upgrading: Since you've heavily customized the theme you have to be careful not to overwrite anything. To fix the issue, you only need to replace `assets/js/hydejack.js`.

**Comment by qwtel** [comment]
Update: You'll also have to update `_sass/hydejack/_menu[-inline].scss` because I've renamed the cryptic `shadow-main` to `animation-main`.

**Comment by mfweber** [comment]
Many thanks for fixing the issue!
Best, Markus
