### ISSUE TITLE
Disable favicon

### ISSUE THREAD

**Issue by selmansamet** [qwtel/hydejack#24]
How can I disable or change favicon? I was edit head.html and change some configs but I didn't can it.

**Comment by qwtel** [comment]
favicons are a surprisingly difficult topic. see [here](https://mathiasbynens.be/notes/rel-shortcut-icon) and [here](https://en.wikipedia.org/wiki/Favicon).

to disable/change the favicon, delete/edit favicon.ico --- that's it. however, your browser keeps the old favicon in cache (seemingly forever) which is why you can't see the change.
