### ISSUE TITLE
Extra long link

### ISSUE THREAD

**Issue by shiv19** [qwtel/hydejack#26]
When i try to open a blog post on my local site
the link looks like this
http://localhost:4000/keyboard/keyboard%20language/lock%20computer/magnifier/minimize%20maximize/on-screen%20keyboard/projection%20settings/shortcuts/super%20menu/system%20info/tips/windows/2015/12/17/14-windows-key-shortcuts-that-you-should-know/

What might be causing this?

**Comment by shiv19** [comment]
Found the problem,
That happened when i added categories tag to my post
so, i changed it from
`categories: [keyboard, keyboard language, lock computer, magnifier, minimize maximize, on-screen keyboard, Projection Settings, shortcuts, Super Menu, system info, Tips, Windows]`

to


`tags: [keyboard, keyboard language, lock computer, magnifier, minimize maximize, on-screen keyboard, Projection Settings, shortcuts, Super Menu, system info, Tips, Windows]`

**Comment by qwtel** [comment]
Yes, that's the way to go 👍 

However, Hydejack's tags aren't really meant to be used in a fire-and-forget manner, "instagram style". There is nothing to prevent you *per-se*, but I guess the reason to add lots of tags is to increase discoverability, for which you could use `keywords` instead. This will render a `<meta name="keywords">` tag in the `<head/>`.

You may also want to add a `description`, which will render a `<meta name="description">` tag, and use a tool like <http://snippetoptimizer.net/> to preview how it would look on Google.

Note that neither of those things will increase your search engine rank dramatically. Instead, I think, it is best to produce good content and share it on other platforms.

As far as Hydejack is concerned, tags and categories are meant for a few re-occurring topics on your blog (more about them [here](https://qwtel.com/hydejack/docs/6.6.1/basics/#adding-a-category-or-tag)).


So you may want to consider something more like this:

~~~
tags: [keyboard, tips]
keywords: [keyboard, keyboard language, lock computer, magnifier, minimize maximize, on-screen keyboard, Projection Settings, shortcuts, Super Menu, system info, Tips, Windows]
description: >
  A short, human-readable description of you post, 
  possibly containing some of your keywords, 
  and that is no more than 156 characters long 
  (will be truncated otherwise).
~~~

**Comment by shiv19** [comment]
Thanks for your suggestions :smile:
