### ISSUE TITLE
Intermittent double render

### ISSUE THREAD

**Issue by woahdae** [qwtel/hydejack#42]
I can't quite pin down exactly when this happens. I've seen it on new page loads with no browser cache, but sometimes new page loads seem to work OK. Most easily reproduced on Safari because Chrome only lets you disable cache with the developer tools open, which can trigger their own weird behaviors. [Here's a repro video](https://drive.google.com/file/d/0B8HbOEjLu787d09FWXpCVkZVeWs/view?usp=sharing).

Also, would it be easy to turn off the fade down animation? I personally find it distracting, and as a bonus you wouldn't notice the double render as much.

**Comment by qwtel** [comment]
thanks for making this repro video! 

okay that took some time to unravel. basically the problem is that these pages are located in `/assets`, and links to it are never intercepted by JS (because they are usually links to images, downloads, etc, not Jekyll pages). 

Free page loads also have a CSS fade-in animation, which mimics the JS animation. When the page is served from cache, it almost looks as if the page was loaded dynamically, because webfonts etc are already applied. Otherwise there is "flickering", as the webfont is applied...

The real question is how pages from the assets folder end up in the Jekyll's pages. Turns out they are actually the `README.md` files for two bower components. I suspect this has to do with building the site on GitHub pages. Apparently, the `jekyll-readme-index` plugin is enabled there, *even* when it's not included in the list of plugins in the config file. When I check out your repo and build it locally it works fine (so [following these build steps](https://qwtel.com/hydejack/docs/7.0.0/build/#building-locally) should work)

Anyway, in the next release I'm going to delete all `*.md` files in the assets folder which should get rid of this as well.
