### ISSUE TITLE
Sidebar image on post 

### ISSUE THREAD

**Issue by RobbiNespu** [qwtel/hydejack#48]
Hi, after upgrading to version 7.3.0 the side bar image does't work anymore
My post are like this
```
layout: post
title: Hello
tags: [personal]
#categories: [robot]
image: '/assets/img/robot.jpg'
```

**Comment by RobbiNespu** [comment]
change `image` to `accent_image` make it worked. How about colors?

**Comment by qwtel** [comment]
This is due to a naming conflict with jekyll-seo-tag.

You can remove jekyll-seo-tag from plugins in your config file and things should go back to how they were.
Otherwise, rename image -> accent_image and color -> accent_color

See also: https://qwtel.com/hydejack/CHANGELOG/#breaking <https://qwtel.com/hydejack/CHANGELOG/#breaking>

Cheers,
Florian

**Comment by qwtel** [comment]
I think this can be closed.
