### ISSUE TITLE
Help with Config

### ISSUE THREAD

**Issue by MaxShalom** [qwtel/hydejack#65]
1. How do I add links to the logos in the sidebar? 
2. Is there a way to have the sidebar background a gradient?

I didn't see these in the docs

**Comment by qwtel** [comment]
1. You mean the social media icons? Look at [`_data/authors.yml`](https://github.com/qwtel/hydejack/blob/master/_data/authors.yml). Note that you can provide arbitrary URLs instead of usernames. Also, this should be part of the docs.

2. You could generate an image for maximal cross-browser compatibility.
    Or, you can provide a CSS gradient like this (this is undocumented, so I reserve the right to change it in the future, but probably won't)

      ```yml
      accent_image:
        background: linear-gradient(to bottom, rgba(240,183,161,1) 0%,rgba(140,51,16,1) 50%,rgba(117,34,1,1) 51%,rgba(191,110,78,1) 100%);
      ```
