### ISSUE TITLE
[Bug/Documentation]: I cannot change the path of the page with blog layout (in PRO version)

### ISSUE THREAD

**Issue by rriemann** [qwtel/hydejack#78]
Hello Florian,

I tried to change the path of my page with blog layout to `/posts` like here https://qwtel.com/posts/ .

For this, I followed the documentation I found here: https://qwtel.com/hydejack/docs/7.5.0/config/#using-the-blog-layout-in-a-subdirectory

However, when I change the path from previously `/blog` to `/posts`, then the blog layout page will show no posts. Only when I delete the file `/posts.md` with `menu: true`, the blog layout page will be populated.

The source of my blog is online at https://github.com/rriemann/blog.riemann.cc/tree/new-blog and I isolated the modification of the path in a pull request here: https://github.com/rriemann/blog.riemann.cc/pull/1

The resulting build with the broken blog layout page can be inspected here: https://5a9c311a7b6ee87d8388c67e--blog-riemann.netlify.com/posts/

**Comment by qwtel** [comment]
I've been able to reproduce the issue. Turns out the solution in the docs is even hackier than I thought and involves the alphabetical/ascii order of the filenames `blog.md` and `index.html`...

Eventually, I'll have to think about a better way to handle sidebar entries. In the meantime you can opt for an even hackier solution and rename `posts.md` to `!posts.md` and add `permalink: /posts/` entry to the front matter

**Comment by rriemann** [comment]
I don't want the exclamation mark interfering with my zsh/bash stuff, so I went for `_posts.md` and added this to my `_config.yml`:

    include:
      - _posts.md
