### ISSUE TITLE
Multiple word tags do not render in title case

### ISSUE THREAD

**Issue by shawnyeager** [qwtel/hydejack#85]
From what I can tell in reviewing `tags-list.html`, the intent is to render tags in title case, however only the first word is capitalized.

If not a bug, suggest implementing.

**Comment by qwtel** [comment]
No, the point of `tags-list.html` is to render the... tags list (sorry 😄). It's in the line below the title and includes the categories: "<date> in Category1 / Category2 on Tag1, Tag2". 

I don't want to force title capitalization, since I've encountered situatons where it would change the meaning, e.g.: "Responsive Web Apps with vw and vh" is referring to the `vw` and `vh` CSS units.
